# Copyright 2018 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

[buildpack]
id = "io.projectriff.riff"
name = "riff Buildpack"
version = "1.0.0-BUILD-SNAPSHOT"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[metadata.dependencies]]
id      = "riff-invoker-java"
name    = "riff Java Invoker"
version = "0.1.0"
uri     = "https://repo.spring.io/libs-milestone-local/io/projectriff/java-function-invoker/0.1.0/java-function-invoker-0.1.0-exec.jar"
sha256  = "03e6fd96711c4a065acaea56e15ce7dcfb2e92d6fd19e3c512c73df9d845db03"
stacks  = [ "io.buildpacks.stacks.bionic" ]